# format = [
#     "conda", "username", "hostname", "directory", "git_branch",
#     "git_commit", "git_state", "git_status",
#     "python","memory_usage", "cmd_duration", "line_break", "jobs",
#     "battery", "time", "character"
# ]

format = """\
$conda\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$package\
$python\
$ruby\
$julia\
$cmd_duration\
$line_break\
$time\
$character\
"""

[username]
style_root = "bold #ef98c9"
style_user = "bold #70a6fe"
show_always = true

[hostname]
style = "bold #86bf86"

[character]
success_symbol = "[ğŸ¦‹](bold) "
error_symbol = "[ğŸ¤¡](bold red) "


[conda]
symbol = " ğŸŒˆ "
# style = "bold #7daafb"
ignore_base = false
format = "[$symbol$environment]($style) "

[directory]
# style = "bold italic"

# [git_status]
# conflicted = " ğŸ³ "
# ahead = " ğŸğŸ’¨ "
# behind = " ğŸ˜° "
# diverged = " ğŸ˜µ"
# untracked = " ğŸ¤·ğŸ»â€â™€ï¸"
# stashed = " ğŸ“¦ "
# modified = " ğŸ“ "
# staged = '[++\($count\)](green)'
# renamed = " ğŸ‘… "
# deleted = " ğŸ—‘ "

# [git_branch]
# symbol = " ğŸ± "

[java]
symbol = "ğŸµ "
# style = "bold italic"
# disabled = true


[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "

[python]
# symbol = "ğŸ "
# style = "bold italic"

# [nodejs]
# format = "via [ğŸ¤– $version](bold) "
